### ISSUE TITLE
combining LaTeXStrings and Strings for labels

### ISSUE THREAD

**Issue by SimonEnsemble** [JuliaPlots/MakieTeX.jl#23]
someone said I should file this issue here. thanks!

https://github.com/JuliaPlots/Makie.jl/issues/1321

**Comment by mschauer** [comment]
lol

**Comment by asinghvi17** [comment]
Hey @SimonEnsemble!  You can now use arbitrary latex as LTeX, which is very similar in application to a Label (see the README for some examples).  You can also swap out Legend labels for LTeX.
