### ISSUE TITLE
LaTeX axis labels?

### ISSUE THREAD

**Issue by mateuszbaran** [JuliaPlots/MakieTeX.jl#3]
Thanks for working on this, no LaTeX support is one of the main reasons I haven't switched to Makie. Would it be possible to have LaTeX in axis labels?

**Comment by asinghvi17** [comment]
Unfortunately, not yet, since this doesn't integrate into the text abstraction.  You could definitely hack around it in MakieLayout, but it would be a pretty complicated hack.

**Comment by AshtonSBradley** [comment]
what would it take to get this and legend latex working?

**Comment by AshtonSBradley** [comment]
MakieTex is now holding back AbstractPlotting so that MakieLayout is not available after the merge. Any way to update compat?

**Comment by MikaelSlevinsky** [comment]
👍 I would definitely like to see this.

**Comment by ederag** [comment]
At least the following allows to display simple text and ticks labels (decimal numbers):
```julia
using FreeTypeAbstraction
Figure(...,
    font=FreeTypeAbstraction.findfont("cmr10")
)
```
Log10 scale superscripts and greek characters currently require an external tool.

Also tried `cmunrm.ttf` and the largest `cmunsl.ttf` from
https://sourceforge.net/projects/cm-unicode/files/cm-unicode/0.7.0/cm-unicode-0.7.0-ttf.tar.xz
but the greek letters are not math style, and superscripts are still missing.

So it is great that there are [plans](https://discourse.julialang.org/t/formatting-plots-with-makie/53034/7) to integrate some LaTeX into Makie (awesome work so far !).

**Comment by ederag** [comment]
Follow-up under Makie.jl: https://github.com/JuliaPlots/Makie.jl/issues/730
Related (general equations): https://github.com/JuliaPlots/Makie.jl/issues/264
