### ISSUE TITLE
Package broken?

### ISSUE THREAD

**Issue by HumpyBlumpy** [JuliaPlots/MakieTeX.jl#41]
Hi and thanks for making this ! it seems like the only option for truly incorporating latex into Makie plots!

I tried running the example in "Quick Start" but it did not work.
Is it something that can be fixed?

**Comment by Lightup1** [comment]
It seems not working on my machine too.
After `using MakieTex`, it do not process latex string by compiling a stand-alone LaTeX document to PDF.
versioninfo:
```julia
julia> versioninfo()
Julia Version 1.8.1
Commit afb6c60d69 (2022-09-06 15:09 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 12 × Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, skylake)
  Threads: 6 on 12 virtual cores
Environment:
  JULIA_NUM_THREADS = 6
  JULIA_PKG_SERVER = https://mirrors.tuna.tsinghua.edu.cn/julia
  JULIA_EDITOR = code
pkg> st Makie MakieTeX
  [ee78f7c6] Makie v0.17.13
  [6d554a22] MakieTeX v0.2.3
```

**Comment by kongdd** [comment]
any progress?
