### ISSUE TITLE
Factor out `MakieTeXCore.jl` without type piracy

### ISSUE THREAD

**Issue by greimel** [JuliaPlots/MakieTeX.jl#42]
Hi @asinghvi17 

Part of this package (`LTeX`, `teximg!`) are really useful even without pirating `text(::LaTeXString)`. This core functionality is probably also easier to maintain than the current package. 

What do you think of either 
* factoring out this functionality (that is, everything, except the bottom part of `text_override.jl`), or
* removing that part altogether for now (because the logic doesn't work with recent Makie versions anymore)

I've played around with this a bit: `LTeX` seems to work as-is by just changing the version bound for CairoMakie. `teximg!` almost works, except that the size is off and that the text is squished (`markerspace = :pixel` seems to be ignored).

## `LTeX`

![image](https://user-images.githubusercontent.com/6280307/211326671-980d5356-325b-435c-83ab-9048c6e4476b.png)

## `teximg!`

![image](https://user-images.githubusercontent.com/6280307/211327975-ff29e699-e39b-4ab3-966d-03304a95bb0d.png)

<s> EDIT: It seems I didn't use the current version of Makie. I'll try again. </s>

**Comment by asinghvi17** [comment]
Definitely possible.  I do want to figure out how we could hook back into text, but for now I could probably comment the text hooks out and release again.

**Comment by asinghvi17** [comment]
Latest master should just work on CairoMakie.  Will push a release out soon as well.
